//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Area()
        {
            this.AreaDetail = new HashSet<AreaDetail>();
            this.AreaDocument = new HashSet<AreaDocument>();
            this.AreaNote = new HashSet<AreaNote>();
            this.AreaPhoto = new HashSet<AreaPhoto>();
            this.AreaProduct = new HashSet<AreaProduct>();
            this.AreaProductDetail = new HashSet<AreaProductDetail>();
            this.AreaProductDocument = new HashSet<AreaProductDocument>();
            this.AreaProductNote = new HashSet<AreaProductNote>();
            this.AreaProductPhoto = new HashSet<AreaProductPhoto>();
        }
    
        public System.Guid AreaKey { get; set; }
        public string AreaName { get; set; }
        public string Reception { get; set; }
        public Nullable<decimal> SquareFeet { get; set; }
        public Nullable<System.Guid> OperationScheduleKey { get; set; }
        public Nullable<System.Guid> NewRateScheduleKey { get; set; }
        public Nullable<System.Guid> CoolingSystemKey { get; set; }
        public Nullable<System.Guid> HeatingSystemKey { get; set; }
        public Nullable<System.Guid> ProjectKey { get; set; }
        public Nullable<System.Guid> ParentAreaKey { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual CoolingSystem CoolingSystem { get; set; }
        public virtual HeatingSystem HeatingSystem { get; set; }
        public virtual NewRateSchedule NewRateSchedule { get; set; }
        public virtual OperatingSchedule OperatingSchedule { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaDetail> AreaDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaDocument> AreaDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaNote> AreaNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaPhoto> AreaPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProduct> AreaProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductDetail> AreaProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductDocument> AreaProductDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductNote> AreaProductNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductPhoto> AreaProductPhoto { get; set; }
    }
}
