//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreaProduct()
        {
            this.AreaProductDetail = new HashSet<AreaProductDetail>();
            this.AreaProductDocument = new HashSet<AreaProductDocument>();
            this.AreaProductNote = new HashSet<AreaProductNote>();
            this.AreaProductPhoto = new HashSet<AreaProductPhoto>();
        }
    
        public System.Guid ProductKey { get; set; }
        public Nullable<System.Guid> AreaKey { get; set; }
        public Nullable<System.Guid> FixtureKey { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public Nullable<int> ForEveryMainQty { get; set; }
        public Nullable<int> ReplaceQty { get; set; }
        public string SolutionName { get; set; }
        public Nullable<System.Guid> IncentiveTypeKey { get; set; }
        public Nullable<decimal> IncentiveAmount { get; set; }
        public Nullable<System.Guid> IncentiveMaxTypeKey { get; set; }
        public Nullable<decimal> IncentiveMaxAmount { get; set; }
        public string ProductName { get; set; }
        public string ModelNo { get; set; }
        public Nullable<decimal> WattPerProduct { get; set; }
        public Nullable<decimal> L70 { get; set; }
        public Nullable<decimal> ThermalEfficency { get; set; }
        public string CustomNotes { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<decimal> MarkupPercentage { get; set; }
        public Nullable<decimal> InstallationTime { get; set; }
        public Nullable<decimal> InstallationCost { get; set; }
        public Nullable<decimal> ShipingCost { get; set; }
        public Nullable<decimal> MiscCost { get; set; }
        public Nullable<decimal> IsOn { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual IncentiveMaxType IncentiveMaxType { get; set; }
        public virtual IncentiveType IncentiveType { get; set; }
        public virtual ProfileProduct ProfileProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductDetail> AreaProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductDocument> AreaProductDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductNote> AreaProductNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductPhoto> AreaProductPhoto { get; set; }
    }
}
