//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaDetail
    {
        public System.Guid DetailKey { get; set; }
        public Nullable<System.Guid> AreaKey { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> AverageIlluminnce { get; set; }
        public Nullable<System.Guid> LightingSatisfactionKey { get; set; }
        public Nullable<decimal> CeilingHeight { get; set; }
        public Nullable<decimal> Reflectance { get; set; }
        public Nullable<decimal> AreaWidth { get; set; }
        public Nullable<decimal> Length { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual LightingSatisfactionFactor LightingSatisfactionFactor { get; set; }
    }
}
