//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaNote
    {
        public System.Guid NoteKey { get; set; }
        public Nullable<System.Guid> AreaKey { get; set; }
        public string NoteContent { get; set; }
        public string Internal { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
