//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaProductDetail
    {
        public System.Guid DetailKey { get; set; }
        public Nullable<System.Guid> AreaKey { get; set; }
        public Nullable<System.Guid> FixtureKey { get; set; }
        public Nullable<System.Guid> ProductKey { get; set; }
        public Nullable<bool> ExistingControl { get; set; }
        public Nullable<System.Guid> OperationScheduleKey { get; set; }
        public Nullable<int> WorkingFixtureCount { get; set; }
        public Nullable<decimal> ReplacementCost { get; set; }
        public Nullable<decimal> AnnualMaintenance { get; set; }
        public Nullable<decimal> InstallationInTime { get; set; }
        public string Location { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.Guid> LightingSatisfactionKey { get; set; }
        public Nullable<decimal> MountingHeight { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual AreaProduct AreaProduct { get; set; }
        public virtual LightingSatisfactionFactor LightingSatisfactionFactor { get; set; }
        public virtual OperatingSchedule OperatingSchedule { get; set; }
        public virtual ProfileProduct ProfileProduct { get; set; }
    }
}
