//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaPhoto
    {
        public System.Guid PhotoKey { get; set; }
        public Nullable<System.Guid> AreaKey { get; set; }
        public string FileType { get; set; }
        public byte[] FileContent { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
