//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCompanyProfileRequest
    {
        public System.Guid RequestID { get; set; }
        public System.Guid ClientCompanyKey { get; set; }
        public System.Guid ProfileKey { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> AdminProfileKey { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
    }
}
