//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeatingSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeatingSystem()
        {
            this.Area = new HashSet<Area>();
        }
    
        public System.Guid HeatingSystemKey { get; set; }
        public Nullable<System.Guid> ProjectKey { get; set; }
        public string SystemName { get; set; }
        public Nullable<decimal> AnnualRunTime { get; set; }
        public Nullable<System.Guid> HeatingSystemTypeKey { get; set; }
        public Nullable<System.Guid> FuelTypeKey { get; set; }
        public Nullable<decimal> FuelCost { get; set; }
        public Nullable<System.Guid> EfficiencyType { get; set; }
        public Nullable<decimal> EfficiencyValue { get; set; }
        public string InternalNote { get; set; }
        public string GeneralNote { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual FuelType FuelType { get; set; }
        public virtual HeatingEfficiencyType HeatingEfficiencyType { get; set; }
        public virtual HeatingSystemType HeatingSystemType { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Area { get; set; }
    }
}
