//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileProduct()
        {
            this.AreaProduct = new HashSet<AreaProduct>();
            this.AreaProductDetail = new HashSet<AreaProductDetail>();
            this.AreaProductDocument = new HashSet<AreaProductDocument>();
            this.AreaProductNote = new HashSet<AreaProductNote>();
            this.AreaProductPhoto = new HashSet<AreaProductPhoto>();
        }
    
        public System.Guid FixtureKey { get; set; }
        public Nullable<System.Guid> ItemTypeKey { get; set; }
        public Nullable<System.Guid> CategoryKey { get; set; }
        public Nullable<System.Guid> SubcategoryKey { get; set; }
        public Nullable<System.Guid> CatelogueKey { get; set; }
        public Nullable<System.Guid> ManufacturerKey { get; set; }
        public string ProductName { get; set; }
        public string ModelNo { get; set; }
        public Nullable<decimal> Watt { get; set; }
        public Nullable<decimal> ThermalEfficacy { get; set; }
        public Nullable<decimal> CRI { get; set; }
        public Nullable<decimal> Lumen { get; set; }
        public Nullable<decimal> LightApparent { get; set; }
        public string Source { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> LightOutput { get; set; }
        public Nullable<decimal> CCT { get; set; }
        public string Size { get; set; }
        public string Location { get; set; }
        public string MountingBase { get; set; }
        public Nullable<System.Guid> ProfileKey { get; set; }
        public byte[] Logo { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> LampLife { get; set; }
        public Nullable<int> TypeCount { get; set; }
        public Nullable<decimal> ThermalEfficiency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProduct> AreaProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductDetail> AreaProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductDocument> AreaProductDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductNote> AreaProductNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProductPhoto> AreaProductPhoto { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemCatelogue ItemCatelogue { get; set; }
        public virtual ItemSubcategory ItemSubcategory { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
