//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Area = new HashSet<Area>();
            this.CoolingSystem = new HashSet<CoolingSystem>();
            this.HeatingSystem = new HashSet<HeatingSystem>();
            this.NewRateSchedule = new HashSet<NewRateSchedule>();
            this.OperatingSchedule = new HashSet<OperatingSchedule>();
            this.Proposal = new HashSet<Proposal>();
            this.Team = new HashSet<Team>();
        }
    
        public System.Guid ProjectKey { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.Guid> ProjectStatusKey { get; set; }
        public Nullable<System.Guid> PrimaryContactKey { get; set; }
        public Nullable<System.Guid> PreparedBy { get; set; }
        public Nullable<int> ExpectedClosingMonth { get; set; }
        public Nullable<int> EspectedClosingYear { get; set; }
        public Nullable<decimal> ProbabilityOfCompletion { get; set; }
        public Nullable<bool> IsAccessableByOthers { get; set; }
        public Nullable<System.Guid> CompanyKey { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Area { get; set; }
        public virtual ClientCompany ClientCompany { get; set; }
        public virtual ClientContact ClientContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoolingSystem> CoolingSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeatingSystem> HeatingSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewRateSchedule> NewRateSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperatingSchedule> OperatingSchedule { get; set; }
        public virtual ProjectStatus ProjectStatus { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal> Proposal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Team { get; set; }
    }
}
