//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalAdditional
    {
        public System.Guid AdditionalKey { get; set; }
        public Nullable<System.Guid> ProjectKey { get; set; }
        public Nullable<System.Guid> ProposalKey { get; set; }
        public decimal ProductMarkup { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<decimal> Misc { get; set; }
        public Nullable<decimal> Incentives { get; set; }
        public Nullable<decimal> LaborHourlyRate { get; set; }
    }
}
