//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalTemplate
    {
        public System.Guid ReportKey { get; set; }
        public Nullable<System.Guid> ProjectKey { get; set; }
        public Nullable<System.Guid> ProposalKey { get; set; }
        public Nullable<System.Guid> TemplateFactorKey { get; set; }
        public Nullable<int> DisplayIndex { get; set; }
    
        public virtual ReportTemplate ReportTemplate { get; set; }
    }
}
