//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        public System.Guid ProposalKey { get; set; }
        public string ProposalName { get; set; }
        public Nullable<System.Guid> ProjectKey { get; set; }
        public Nullable<System.Guid> PreparedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] Pic { get; set; }
        public string PicType { get; set; }
        public string Picname { get; set; }
        public string PageInfo { get; set; }
        public string IntroductionText { get; set; }
        public string Team { get; set; }
        public string Legal { get; set; }
        public string Disclaimer { get; set; }
        public string Reference { get; set; }
        public string Billing { get; set; }
        public string Notes { get; set; }
        public string Summary { get; set; }
        public string Estimal { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string PreparedByText { get; set; }
        public Nullable<decimal> MarkupPercentage { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public Nullable<decimal> MiscCost { get; set; }
        public Nullable<decimal> TaxIncentives { get; set; }
        public Nullable<decimal> ProductMargin { get; set; }
        public Nullable<decimal> Incentives { get; set; }
        public Nullable<decimal> InstallationRates { get; set; }
        public Nullable<decimal> TaxInput { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
