//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NasgledSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public System.Guid TeamKey { get; set; }
        public System.Guid ClientCompanyKey { get; set; }
        public Nullable<System.Guid> ProfileKey { get; set; }
        public Nullable<System.Guid> RoleKey { get; set; }
        public Nullable<System.Guid> JobFunctionKey { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> ProjectKey { get; set; }
    
        public virtual JobFunction JobFunction { get; set; }
        public virtual Project Project { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ClientCompany ClientCompany { get; set; }
    }
}
